name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Use jsonlog token
        run: |
          git config --global url."https://${{ secrets.JSONLOG_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
          export GOPRIVATE=github.com/NextronSystems/*
      - name: Install dependencies
        run: go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
